//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vet.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cheque
    {
        public int IDCheque { get; set; }
        public decimal Price { get; set; }
        public Nullable<int> IDApp { get; set; }
        public System.DateTime ChequeDate { get; set; }
        public string DepAddress { get; set; }
    
        public virtual Appointment Appointment { get; set; }
    }
}
